#EXEC, INPUT, MISC
source =~/.config/hypr/modules/general.conf
#DECORATION ASPECTS
source =~/.config/hypr/modules/decoration.conf
#ENVIROMENTAL VARIABLES
source =~/.config/hypr/modules/env.conf
#DECORATION ASPECTS
source =~/.config/hypr/modules/decoration.conf
#BINDINGS APPS
source =~/.config/hypr/modules/binds.conf
#WINDOW RULES
source =~/.config/hypr/modules/rules.conf

