source=$HOME/.config/hypr/themes/mocha.conf

monitor=eDP-1,2880x1800@120,0x0,1.5,

exec-once = waybar & hyprpaper & firefox
exec = ~/.config/waybar/scripts/refresh.sh
# Source a file (multi-file configs)
source = ~/.config/hypr/themes/mocha.conf
exec = hyprpaper
# Set programs that you use
input {
    kb_layout = es
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 4
    gaps_out = 10
    border_size = 4
    col.active_border = $teal
    col.inactive_border = rgba(595959aa)

    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = true
    env = WLR_DRM_NO_ATOMIC,1
    windowrulev2 = immediate,class:^(cs2)$
}


dwindle {
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

misc {
  disable_splash_rendering = true
  disable_hyprland_logo = true


}
